### ISSUE TITLE
Conflict with icon name

### ISSUE THREAD

**Issue by Liam0205** [revir/need-more-share2#1]
Hi @revir ,

Thank you for your time, and need-more-share2 is a great work!

I've notice that, in the file `fontello-embedded.css`, font settings for all `icon-` classes is set to be `fontello`. This is almost right, however, could be making conflict sometimes.

For example, if one uses `icon-fa-heart` in his/her HTML documents, `fontello` would be applied. However, `icon-fa-heart` is not declared in the very font. As a result, a blank block would be presented, which is medusa.

This is because of a not-carefully-set namespace. I suppose that, icons used by need-more-share2 should be in a specific naming scheme, say `icon-nms-*`. Hence, you could easily apply the font family `fontello` to all and exact icons you want.

Bless.

LH

**Comment by revir** [comment]
Thanks.
I added a prefix name to the font family. It should be fixed.

**Comment by Liam0205** [comment]
Actually, commit ad7f797 does not fix this issue.

CSS files that users will load, say `needsharebutton.css` or `needsharebutton.min.css`, stay unchanged.

You may need to regenerate `needsharebutton.min.css` for the very fix.

**Comment by revir** [comment]
yeah, but actually needsharebutton.css imports fontello-embedded.css, no
need to change needsharebutton.css, but to use it, you have to put
fontello-embedded.css
in the right place with needsharebutton.css.


I just added a prefix class to the font-family style, but didn't change the
class name of icons (say: icon-heart to icon-nms-heart), could the class
names cause this problem?



--------------
*River*

2017-04-27 3:03 GMT+08:00 Liam Huang <notifications@github.com>:

**Comment by Liam0205** [comment]
Yes indeed, `needsharebutton.css` is fair enouth, however, 

> You may need to regenerate `needsharebutton.min.css` for the very fix.

Let's have a look at what's is now left in `needsharebutton.min.css`.

```css
@font-face{font-family:fontello;src:url(../font/fontello.eot?13586373);src:url(../font/fontello.eot?13586373#iefix) format('embedded-opentype'),url(../font/fontello.svg?13586373#fontello) format('svg');font-weight:400;font-style:normal}@font-face{font-family:fontello;src:url(data:application/octet-stream;base64,
...
format('truetype')}[class*=" icon-"]:before,[class^=icon-]:before{font-family:fontello;font-style:normal;font-weight:400;speak:none;display:inline-block;text-decoration:inherit;width:1em;margin-right:.2em;text-align:center;font-variant:normal;text-transform:none;line-height:1em;margin-left:.2em}.icon-heart:before{content:'\e800'}.icon-heart-empty:before{content:'\e801'}.
...
```

You should have noticed that everything in `needsharebutton.min.css` stays unchanged and needs to be regenerated.

**Comment by revir** [comment]
Oh thank you so much! I didn't know needsharebutton.min.css has included
fontello.embed.css! You taught me a lesson! Thank you so much!


--------------
*River*

2017-04-27 13:33 GMT+08:00 Liam Huang <notifications@github.com>:

**Comment by Liam0205** [comment]
Great Job!
